import numpy as np
import pandas as pd

from src.model.distance import bng_distance


def model_2(origins_df: pd.DataFrame,
            destinations_df: pd.DataFrame,
            visits_per_person: float,
            lambda_value: float) -> pd.DataFrame:
    """
    Baseline distance-only spatial interaction model (M2).

    Uses the same decay convention as src.behaviour.distance_decay and
    src.model.quality_attractor: weight = exp(-lambda_value * distance),
    with lambda_value expressed per metre (NOT a metre length-scale).

    Parameters
    ----------
    origins_df : pd.DataFrame
        Must contain columns: origin_id, E, N, population.
    destinations_df : pd.DataFrame
        Must contain columns: access_pt_id, E, N.
    visits_per_person : float
        Annual visits per person (placeholder).
    lambda_value : float
        Distance-decay rate, per metre. weight = exp(-lambda_value * distance).

    Returns
    -------
    pd.DataFrame
        Long-format OD table with columns: origin_id, access_pt_id, visits.
    """
    origins = origins_df.copy()
    destinations = destinations_df.copy()

    # Total visits generated by each origin
    origins["total_visits"] = origins["population"] * visits_per_person

    # Cartesian product: every origin paired with every destination
    origins_cp = origins.rename(columns={"E": "E_o", "N": "N_o"})
    dest_cp = destinations.rename(columns={"E": "E_d", "N": "N_d"})

    df = origins_cp.assign(key=1).merge(dest_cp.assign(key=1), on="key").drop("key", axis=1)

    # Compute Euclidean distance
    df["distance"] = bng_distance(df["E_o"], df["N_o"], df["E_d"], df["N_d"])

    # Exponential decay weight
    df["weight"] = np.exp(-df["distance"] * lambda_value)

    # Sum of weights per origin (for normalisation)
    weight_sums = df.groupby("origin_id")["weight"].sum().rename("weight_sum")
    df = df.merge(weight_sums, on="origin_id")

    # Allocate visits proportionally to weight
    df["visits"] = df["total_visits"] * (df["weight"] / df["weight_sum"])

    return df[["origin_id", "access_pt_id", "visits"]]
