import numpy as np
import pandas as pd

from src.model.distance import bng_distance, load_network_distances


def model_2(origins_df: pd.DataFrame,
            destinations_df: pd.DataFrame,
            visits_per_person: float,
            lambda_value: float,
            distance_method: str = "euclidean",
            network_distances_path=None) -> pd.DataFrame:
    """
    Baseline distance-only spatial interaction model (M2).

    Uses the same decay convention as src.behaviour.distance_decay and
    src.model.quality_attractor: weight = exp(-lambda_value * distance),
    with lambda_value expressed per metre (NOT a metre length-scale).

    Destinations are access-point-level (multiple access points per site_id)
    but a site's distance from an origin is reduced to the distance to its
    NEAREST access point before weighting/allocation, so sites don't compete
    in proportion to how many access points they happen to have.

    Parameters
    ----------
    origins_df : pd.DataFrame
        Must contain columns: origin_id, E, N, population.
    destinations_df : pd.DataFrame
        Must contain columns: access_pt_id, site_id, E, N.
    visits_per_person : float
        Annual visits per person (placeholder).
    lambda_value : float
        Distance-decay rate, per metre. weight = exp(-lambda_value * distance).
    distance_method : "euclidean" | "network"
        "euclidean" (default) computes straight-line BNG distance, as
        before. "network" loads pre-computed OSRM distances from
        `network_distances_path` (see paths_cfg.DISTANCES_FINAL_WALK /
        DISTANCES_FINAL_DRIVE - drive covers LAMBDA_PANS's range, walk
        currently caps at ~2.16km, see paths_cfg for the full caveat) and
        re-maps them to the current site_id scheme via destinations_df.
        Origin/destination pairs with no OSRM row (outside its threshold,
        or not matched by access_pt_id) simply don't appear - there is no
        fallback to Euclidean for those pairs.
    network_distances_path : path-like, required if distance_method="network"
        Path to a distances_final.parquet file.

    Returns
    -------
    pd.DataFrame
        Long-format OD table with columns: origin_id, site_id, visits.
    """
    origins = origins_df.copy()
    destinations = destinations_df.copy()

    # Total visits generated by each origin
    origins["total_visits"] = origins["population"] * visits_per_person

    if distance_method == "euclidean":
        # Cartesian product: every origin paired with every destination
        origins_cp = origins.rename(columns={"E": "E_o", "N": "N_o"})
        dest_cp = destinations.rename(columns={"E": "E_d", "N": "N_d"})

        df = origins_cp.assign(key=1).merge(dest_cp.assign(key=1), on="key").drop("key", axis=1)

        # Compute Euclidean distance
        df["distance"] = bng_distance(df["E_o"], df["N_o"], df["E_d"], df["N_d"])
        df = df[["origin_id", "site_id", "distance"]]

    elif distance_method == "network":
        if network_distances_path is None:
            raise ValueError(
                "network_distances_path is required when distance_method='network' "
                "(see paths_cfg.DISTANCES_FINAL_WALK / DISTANCES_FINAL_DRIVE)"
            )
        df = load_network_distances(
            distances_path=network_distances_path,
            destinations_df=destinations,
            origin_ids=origins["origin_id"].unique(),
        )

    else:
        raise ValueError(
            f"Unknown distance_method: {distance_method!r} "
            "(expected 'euclidean' or 'network')"
        )

    # --- collapse access points down to one distance per site ---
    # A site's distance from an origin is the distance to its NEAREST
    # access point, not every access point competing as its own destination.
    df = (
        df.groupby(["origin_id", "site_id"], as_index=False)["distance"]
          .min()
          .merge(origins[["origin_id", "total_visits"]], on="origin_id")
    )
    # --- end ---

    # Exponential decay weight
    df["weight"] = np.exp(-df["distance"] * lambda_value)

    # Sum of weights per origin (for normalisation)
    weight_sums = df.groupby("origin_id")["weight"].sum().rename("weight_sum")
    df = df.merge(weight_sums, on="origin_id")

    # Allocate visits proportionally to weight
    df["visits"] = df["total_visits"] * (df["weight"] / df["weight_sum"])

    return df[["origin_id", "site_id", "visits"]]